include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unintended_html_in_doc_comment: ignore
  plugins:
    - custom_lint
  exclude: ["**/*.g.dart", "**/*.freezed.dart"]

formatter:
  trailing_commas: preserve
  page_width: 120

linter:
  rules:
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    always_use_package_imports: false
    one_member_abstracts: false

    prefer_relative_imports: true
    avoid_relative_lib_imports: true
