include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  exclude: ["**/*.g.dart", "**/*.freezed.dart"]

  # language:
  #   strict-casts: true
  #   strict-inference: true
  #   strict-raw-types: true

  errors:
    avoid_catches_without_on_clauses: ignore
    avoid_print: ignore
    document_ignores: ignore
    invalid_annotation_target: ignore
    missing_required_param: error
    missing_return: error

formatter:
  trailing_commas: preserve
  page_width: 120

linter:
  rules:
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    always_use_package_imports: false
    one_member_abstracts: false

    prefer_relative_imports: true
    avoid_relative_lib_imports: true
