name: ikki_pos_flutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: 3.32.1

dependencies:
  bson: ^5.0.7
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  data_table_2: ^2.6.0
  device_info_plus: ^12.1.0
  dio: ^5.8.0+1
  esc_pos_utils_plus: ^2.0.4
  flex_color_scheme: ^8.2.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_keyboard_visibility: ^6.0.0
  flutter_riverpod: ^3.0.0-dev.17
  flutter_screenutil: ^5.9.3
  flutter_thermal_printer: ^1.2.1+1
  fpdart: ^1.1.1
  freezed_annotation: ^3.0.0
  go_router: ^16.0.0
  go_transitions: ^0.8.1
  google_fonts: ^6.2.1
  http: ^1.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  keyboard_service: ^2.0.3
  mqtt_client: ^10.11.1
  objectid: ^4.0.1
  onesignal_flutter: ^5.1.2
  permission_handler: ^12.0.1
  pinput: ^5.0.1
  queue: ^3.4.0
  riverpod_annotation: ^3.0.0-dev.17
  scaled_app: ^2.3.0
  sembast: ^3.8.5+1
  sembast_sqflite: ^2.2.1
  sentry_flutter: ^9.6.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  talker: ^5.0.1
  talker_dio_logger: ^5.0.1
  talker_flutter: ^5.0.1

dev_dependencies:
  build_runner: ^2.4.15
  build_verify: ^3.1.1
  custom_lint: ^0.8.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  riverpod_generator: ^3.0.0-dev.17
  riverpod_lint: ^3.0.0-dev.17
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mock/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Bold.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
