name: ikki_pos_flutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Core
  go_router: ^15.1.3
  go_transitions: ^0.8.1
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  freezed_annotation: ^3.0.0
  json_serializable: ^6.9.5
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1

  # State Management
  riverpod_annotation: ^3.0.0-dev.15
  flutter_riverpod: ^3.0.0-dev.15

  # Local Database
  sembast:
  sembast_sqflite:
  sqflite:

  # UI
  cupertino_icons: ^1.0.8
  pinput: ^5.0.1

  # Util
  fpdart: ^1.1.1
  intl: ^0.20.2
  bson: ^5.0.7
  device_info_plus: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  build_verify: any
  custom_lint: ^0.7.5
  riverpod_lint: ^3.0.0-dev.15
  riverpod_generator: ^3.0.0-dev.15
  freezed: ^3.0.6
  go_router_builder: any

flutter:
  uses-material-design: true
  assets:
    - assets/mock/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Bold.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
