import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

abstract final class AppThemeFlex {
  // The FlexColorScheme defined light mode ThemeData.
  static ThemeData light = FlexThemeData.light(
    scheme: FlexScheme.shadBlue,
    swapLegacyOnMaterial3: true,
    // Surface color adjustments.
    lightIsWhite: true,
    // Convenience direct styling properties.
    appBarElevation: 2,
    bottomAppBarElevation: 0.5,
    // Component theme configurations for light mode.
    subThemesData: const FlexSubThemesData(
      interactionEffects: true,
      blendOnLevel: 10,
      useMaterial3Typography: true,
      useM2StyleDividerInM3: true,
      thinBorderWidth: 1,
      splashTypeAdaptive: FlexSplashType.instantSplash,
      adaptiveAppBarScrollUnderOff: FlexAdaptive.all(),
      defaultRadius: 8,
      elevatedButtonSecondarySchemeColor: SchemeColor.secondary,
      outlinedButtonOutlineSchemeColor: SchemeColor.primary,
      toggleButtonsBorderSchemeColor: SchemeColor.outlineVariant,
      segmentedButtonSchemeColor: SchemeColor.primary,
      segmentedButtonBorderSchemeColor: SchemeColor.outlineVariant,
      switchThumbSchemeColor: SchemeColor.onPrimaryContainer,
      switchAdaptiveCupertinoLike: FlexAdaptive.all(),
      unselectedToggleIsColored: true,
      sliderValueTinted: true,
      sliderTrackHeight: 8,
      inputDecoratorIsDense: true,
      inputDecoratorContentPadding: EdgeInsetsDirectional.fromSTEB(12, 12, 12, 12),
      inputDecoratorBorderSchemeColor: SchemeColor.primary,
      inputDecoratorBorderType: FlexInputBorderType.outline,
      inputDecoratorRadius: 8,
      inputDecoratorBorderWidth: 0.5,
      inputDecoratorFocusedBorderWidth: 2,
      fabSchemeColor: SchemeColor.primary,
      chipSchemeColor: SchemeColor.transparent,
      chipSelectedSchemeColor: SchemeColor.primary,
      chipDeleteIconSchemeColor: SchemeColor.error,
      chipFontSize: 12,
      chipIconSize: 10,
      chipPadding: EdgeInsetsDirectional.fromSTEB(4, 4, 4, 4),
      cardRadius: 8,
      popupMenuRadius: 8,
      popupMenuElevation: 1,
      popupMenuSchemeColor: SchemeColor.onPrimary,
      alignedDropdown: true,
      tooltipRadius: 6,
      tooltipSchemeColor: SchemeColor.surfaceContainerHigh,
      tooltipOpacity: 0.96,
      dialogBackgroundSchemeColor: SchemeColor.surfaceContainerHigh,
      dialogElevation: 1,
      dialogRadius: 8,
      snackBarRadius: 8,
      snackBarElevation: 4,
      snackBarBackgroundSchemeColor: SchemeColor.surfaceTint,
      snackBarActionSchemeColor: SchemeColor.inversePrimary,
      appBarBackgroundSchemeColor: SchemeColor.primary,
      appBarForegroundSchemeColor: SchemeColor.onPrimary,
      appBarIconSchemeColor: SchemeColor.onPrimary,
      appBarActionsIconSchemeColor: SchemeColor.onPrimary,
      appBarScrolledUnderElevation: 3,
      appBarCenterTitle: false,
      bottomAppBarSchemeColor: SchemeColor.primary,
      bottomAppBarHeight: 60,
      tabBarUnselectedItemOpacity: 0.59,
      tabBarIndicatorWeight: 5,
      tabBarIndicatorTopRadius: 10,
      tabBarDividerColor: Color(0x00000000),
      tabBarIndicatorAnimation: TabIndicatorAnimation.elastic,
      drawerRadius: 8,
      drawerElevation: 10,
      drawerIndicatorSchemeColor: SchemeColor.primary,
      drawerUnselectedItemSchemeColor: SchemeColor.tertiary,
      bottomSheetBackgroundColor: SchemeColor.surfaceContainerHigh,
      bottomSheetModalBackgroundColor: SchemeColor.surfaceContainer,
      bottomSheetRadius: 12,
      bottomSheetElevation: 4,
      bottomSheetModalElevation: 6,
      bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.primary,
      bottomNavigationBarMutedUnselectedLabel: true,
      bottomNavigationBarSelectedIconSchemeColor: SchemeColor.primary,
      bottomNavigationBarMutedUnselectedIcon: true,
      bottomNavigationBarBackgroundSchemeColor: SchemeColor.surfaceContainer,
      bottomNavigationBarElevation: 0,
      menuRadius: 6,
      menuElevation: 4,
      menuPadding: EdgeInsetsDirectional.fromSTEB(6, 10, 5, 10),
      menuBarRadius: 0,
      menuBarElevation: 0,
      menuBarShadowColor: Color(0x00000000),
      menuIndicatorBackgroundSchemeColor: SchemeColor.surfaceContainerHigh,
      menuIndicatorRadius: 6,
      searchBarElevation: 0,
      searchViewElevation: 0,
      searchBarRadius: 8,
      searchViewRadius: 8,
      searchViewHeaderHeight: 48,
      navigationBarIndicatorSchemeColor: SchemeColor.secondaryContainer,
      navigationBarBackgroundSchemeColor: SchemeColor.surfaceContainer,
      navigationBarElevation: 0,
      navigationBarHeight: 72,
      navigationRailUseIndicator: true,
      navigationRailIndicatorSchemeColor: SchemeColor.secondaryContainer,
      navigationRailIndicatorOpacity: 1,
      navigationRailBackgroundSchemeColor: SchemeColor.surfaceContainer,
    ),
    // ColorScheme seed generation configuration for light mode.
    keyColors: const FlexKeyColors(
      useSecondary: true,
      useTertiary: true,
      useError: true,
      keepPrimary: true,
      keepSecondary: true,
      keepError: true,
      keepTertiaryContainer: true,
    ),
    tones: FlexSchemeVariant.chroma.tones(Brightness.light).higherContrastFixed().monochromeSurfaces(),
    // Direct ThemeData properties.
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
  );

  // The FlexColorScheme defined dark mode ThemeData.
  static ThemeData dark = FlexThemeData.dark(
    // Using FlexColorScheme built-in FlexScheme enum based colors.
    scheme: FlexScheme.shadBlue,
    // Input color modifiers.
    swapLegacyOnMaterial3: true,
    // Convenience direct styling properties.
    bottomAppBarElevation: 0.5,
    // Component theme configurations for dark mode.
    subThemesData: const FlexSubThemesData(
      interactionEffects: true,
      blendOnLevel: 20,
      blendOnColors: true,
      useMaterial3Typography: true,
      useM2StyleDividerInM3: true,
      splashTypeAdaptive: FlexSplashType.instantSplash,
      adaptiveElevationShadowsBack: FlexAdaptive.all(),
      adaptiveAppBarScrollUnderOff: FlexAdaptive.all(),
      defaultRadius: 8,
      thinBorderWidth: 1,
      elevatedButtonSecondarySchemeColor: SchemeColor.secondary,
      outlinedButtonOutlineSchemeColor: SchemeColor.primary,
      toggleButtonsBorderSchemeColor: SchemeColor.outlineVariant,
      segmentedButtonSchemeColor: SchemeColor.primary,
      segmentedButtonBorderSchemeColor: SchemeColor.outlineVariant,
      switchThumbSchemeColor: SchemeColor.onPrimaryContainer,
      switchAdaptiveCupertinoLike: FlexAdaptive.all(),
      unselectedToggleIsColored: true,
      sliderValueTinted: true,
      sliderTrackHeight: 8,
      inputDecoratorIsDense: true,
      inputDecoratorContentPadding: EdgeInsetsDirectional.fromSTEB(12, 12, 12, 12),
      inputDecoratorBorderSchemeColor: SchemeColor.primary,
      inputDecoratorBorderType: FlexInputBorderType.outline,
      inputDecoratorRadius: 8,
      inputDecoratorBorderWidth: 0.5,
      inputDecoratorFocusedBorderWidth: 2,
      fabSchemeColor: SchemeColor.primary,
      chipSchemeColor: SchemeColor.transparent,
      chipSelectedSchemeColor: SchemeColor.primary,
      chipDeleteIconSchemeColor: SchemeColor.error,
      chipFontSize: 12,
      chipIconSize: 16,
      chipPadding: EdgeInsetsDirectional.fromSTEB(4, 4, 4, 4),
      cardRadius: 8,
      popupMenuRadius: 8,
      popupMenuElevation: 1,
      popupMenuSchemeColor: SchemeColor.onPrimary,
      alignedDropdown: true,
      tooltipRadius: 6,
      tooltipSchemeColor: SchemeColor.surfaceContainerHigh,
      tooltipOpacity: 0.96,
      dialogBackgroundSchemeColor: SchemeColor.surfaceContainerHigh,
      dialogElevation: 1,
      dialogRadius: 8,
      snackBarRadius: 8,
      snackBarElevation: 4,
      snackBarBackgroundSchemeColor: SchemeColor.surfaceTint,
      snackBarActionSchemeColor: SchemeColor.inversePrimary,
      appBarBackgroundSchemeColor: SchemeColor.surfaceContainerLowest,
      appBarScrolledUnderElevation: 2.5,
      appBarCenterTitle: false,
      bottomAppBarHeight: 60,
      tabBarIndicatorWeight: 5,
      tabBarIndicatorTopRadius: 10,
      tabBarDividerColor: Color(0x00000000),
      tabBarIndicatorAnimation: TabIndicatorAnimation.elastic,
      drawerRadius: 8,
      drawerElevation: 10,
      drawerIndicatorSchemeColor: SchemeColor.primary,
      drawerUnselectedItemSchemeColor: SchemeColor.tertiary,
      bottomSheetBackgroundColor: SchemeColor.surfaceContainerHigh,
      bottomSheetModalBackgroundColor: SchemeColor.surfaceContainer,
      bottomSheetRadius: 12,
      bottomSheetElevation: 4,
      bottomSheetModalElevation: 6,
      bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.primary,
      bottomNavigationBarMutedUnselectedLabel: true,
      bottomNavigationBarSelectedIconSchemeColor: SchemeColor.primary,
      bottomNavigationBarMutedUnselectedIcon: true,
      bottomNavigationBarBackgroundSchemeColor: SchemeColor.surfaceContainer,
      bottomNavigationBarElevation: 0,
      menuRadius: 6,
      menuElevation: 4,
      menuPadding: EdgeInsetsDirectional.fromSTEB(6, 10, 5, 10),
      menuBarRadius: 0,
      menuBarElevation: 0,
      menuBarShadowColor: Color(0x00000000),
      menuIndicatorBackgroundSchemeColor: SchemeColor.surfaceContainerHigh,
      menuIndicatorRadius: 6,
      searchBarElevation: 0,
      searchViewElevation: 0,
      searchBarRadius: 8,
      searchViewRadius: 8,
      searchViewHeaderHeight: 48,
      navigationBarIndicatorSchemeColor: SchemeColor.secondaryContainer,
      navigationBarBackgroundSchemeColor: SchemeColor.surfaceContainer,
      navigationBarElevation: 0,
      navigationBarHeight: 72,
      navigationRailUseIndicator: true,
      navigationRailIndicatorSchemeColor: SchemeColor.secondaryContainer,
      navigationRailIndicatorOpacity: 1,
      navigationRailBackgroundSchemeColor: SchemeColor.surfaceContainer,
    ),
    // ColorScheme seed configuration setup for dark mode.
    keyColors: const FlexKeyColors(
      useSecondary: true,
      useTertiary: true,
      useError: true,
      keepPrimary: true,
      keepSecondary: true,
      keepError: true,
      keepTertiaryContainer: true,
    ),
    tones: FlexSchemeVariant.chroma.tones(Brightness.dark).higherContrastFixed().monochromeSurfaces(),
    // Direct ThemeData properties.
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
  );
}
